% whose subject-data are we using
file_osim_array   = {'fullbody7.osim'};
file_osim_array   = {'staticP032_fullbody7_SCALED.osim', ...
    'staticP042_fullbody7_SCALED.osim', ...
    'staticP052_fullbody7_SCALED.osim', ...
    'staticP062_fullbody7_SCALED.osim', ...
    'staticP072_fullbody7_SCALED.osim', ...
    'staticP082_fullbody7_SCALED.osim', ...
    'staticP092_fullbody7_SCALED.osim', ...
    'staticP102_fullbody7_SCALED.osim', ...
    'staticP112_fullbody7_SCALED.osim', ...
    'staticP122_fullbody7_SCALED.osim'};
path_osim   = 'C:\Users\lsboe\Documents\gait_simulation_package\skeletal_models\';
file_c3d_array    = {'staticP072.c3d'};
file_c3d_array    = {'normalP032.c3d', ...
    'normalP042.c3d', ...
    'normalP052.c3d', ...
    'normalP062.c3d', ...
    'normalP072.c3d', ...
    'normalP082.c3d', ...
    'normalP092.c3d', ...
    'normalP102.c3d', ...
    'normalP112.c3d', ...
    'normalP122.c3d'};
path_c3d    = 'C:\Users\lsboe\Documents\gait_simulation_package\experimental_data\';
massmat = [72];% % Shortcuts